<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'dapr.actors.proxy.generation' => 'get1',
  'dapr.subscriptions' => 'get2',
  'subEntry1' => 'get3',
  'dapr.actors' => 'get4',
  'dapr.actors.idle_timeout' => 'get5',
  'dapr.actors.scan_interval' => 'get6',
  'dapr.actors.drain_timeout' => 'get7',
  'dapr.actors.drain_enabled' => 'get8',
  'dapr.port' => 'get9',
  'dapr.serializers.custom' => 'get10',
  'dapr.deserializers.custom' => 'get11',
  'dapr.log.level' => 'get12',
  'dapr.log.handler' => 'get13',
  'subEntry2' => 'get14',
  'subEntry3' => 'get15',
  'dapr.log.processor' => 'get16',
  'subEntry4' => 'get17',
  'Psr\\Log\\LoggerInterface' => 'get18',
  'subEntry5' => 'get19',
  'subEntry6' => 'get20',
  'Dapr\\Deserialization\\IDeserializer' => 'get21',
  'subEntry7' => 'get22',
  'subEntry8' => 'get23',
  'Dapr\\Serialization\\ISerializer' => 'get24',
  'subEntry9' => 'get25',
  'subEntry10' => 'get26',
  'Dapr\\State\\IManageState' => 'get27',
  'subEntry11' => 'get28',
  'subEntry12' => 'get29',
  'subEntry13' => 'get30',
  'subEntry14' => 'get31',
  'Dapr\\Actors\\Generators\\ProxyFactory' => 'get32',
  'subEntry15' => 'get33',
  'subEntry16' => 'get34',
  'Dapr\\PubSub\\Subscriptions' => 'get35',
  'subEntry17' => 'get36',
  'Dapr\\Actors\\ActorConfig' => 'get37',
  'subEntry18' => 'get38',
  'subEntry19' => 'get39',
  'subEntry20' => 'get40',
  'subEntry21' => 'get41',
  'subEntry22' => 'get42',
  'Dapr\\DaprClient' => 'get43',
  'subEntry23' => 'get44',
  'subEntry24' => 'get45',
  'subEntry25' => 'get46',
  'Dapr\\Serialization\\SerializationConfig' => 'get47',
  'subEntry26' => 'get48',
  'Dapr\\Deserialization\\DeserializationConfig' => 'get49',
  'subEntry27' => 'get50',
  'Dapr\\Actors\\ActorProxy' => 'get51',
  'subEntry28' => 'get52',
  'subEntry29' => 'get53',
  'Dapr\\PubSub\\Publish' => 'get54',
  'subEntry30' => 'get55',
  'subEntry31' => 'get56',
  'Dapr\\Actors\\ActorRuntime' => 'get57',
  'subEntry32' => 'get58',
  'subEntry33' => 'get59',
  'subEntry34' => 'get60',
  'subEntry35' => 'get61',
  'dapr.pubsub.default' => 'get62',
);

    protected function get1()
    {
        return 0;
    }

    protected function get3()
    {
        return $this->resolveFactory(static fn() => new \Dapr\PubSub\Subscription('pubsub', 'receive', '/events/receivedItem')
        , 'subEntry1');
    }

    protected function get2()
    {
        return [
            0 => $this->get3(),
        ];
    }

    protected function get4()
    {
        return [
            0 => 'Picker\\Actors\\Inventory\\InventoryActor',
            1 => 'Picker\\Actors\\Bin\\BinActor',
        ];
    }

    protected function get5()
    {
        return NULL;
    }

    protected function get6()
    {
        return NULL;
    }

    protected function get7()
    {
        return NULL;
    }

    protected function get8()
    {
        return NULL;
    }

    protected function get9()
    {
                $value = getenv('DAPR_HTTP_PORT');
        if (false !== $value) return $value;
        if (!true) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'DAPR_HTTP_PORT' has not been defined");
        }
        return '3500';
    }

    protected function get10()
    {
        return [
        ];
    }

    protected function get11()
    {
        return [
        ];
    }

    protected function get12()
    {
        return 'warning';
    }

    protected function get15()
    {
        return $this->delegateContainer->get('dapr.log.level');
    }

    protected function get14()
    {
        $object = new Monolog\Handler\ErrorLogHandler(0, $this->get15(), true, false);
        return $object;
    }

    protected function get13()
    {
        return [
            0 => $this->get14(),
        ];
    }

    protected function get17()
    {
        $object = new Monolog\Processor\PsrLogMessageProcessor(NULL, false);
        return $object;
    }

    protected function get16()
    {
        return [
            0 => $this->get17(),
        ];
    }

    protected function get19()
    {
        return $this->delegateContainer->get('dapr.log.handler');
    }

    protected function get20()
    {
        return $this->delegateContainer->get('dapr.log.processor');
    }

    protected function get18()
    {
        $object = new Monolog\Logger('DAPR', $this->get19(), $this->get20(), NULL);
        return $object;
    }

    protected function get22()
    {
        return $this->delegateContainer->get('Dapr\\Deserialization\\DeserializationConfig');
    }

    protected function get23()
    {
        return $this->delegateContainer->get('Psr\\Log\\LoggerInterface');
    }

    protected function get21()
    {
        $object = new Dapr\Deserialization\Deserializer($this->get22(), $this->get23());
        return $object;
    }

    protected function get25()
    {
        return $this->delegateContainer->get('Dapr\\Serialization\\SerializationConfig');
    }

    protected function get26()
    {
        return $this->delegateContainer->get('Psr\\Log\\LoggerInterface');
    }

    protected function get24()
    {
        $object = new Dapr\Serialization\Serializer($this->get25(), $this->get26());
        return $object;
    }

    protected function get28()
    {
        return $this->delegateContainer->get('Psr\\Log\\LoggerInterface');
    }

    protected function get29()
    {
        return $this->delegateContainer->get('Dapr\\Serialization\\ISerializer');
    }

    protected function get30()
    {
        return $this->delegateContainer->get('Dapr\\Deserialization\\IDeserializer');
    }

    protected function get31()
    {
        return $this->delegateContainer->get('Dapr\\DaprClient');
    }

    protected function get27()
    {
        $object = new Dapr\State\StateManager($this->get28(), $this->get29(), $this->get30(), $this->get31());
        return $object;
    }

    protected function get33()
    {
        return $this->delegateContainer->get('DI\\FactoryInterface');
    }

    protected function get34()
    {
        return $this->delegateContainer->get('dapr.actors.proxy.generation');
    }

    protected function get32()
    {
        $object = new Dapr\Actors\Generators\ProxyFactory($this->get33(), $this->get34());
        return $object;
    }

    protected function get36()
    {
        return $this->delegateContainer->get('dapr.subscriptions');
    }

    protected function get35()
    {
        $object = new Dapr\PubSub\Subscriptions($this->get36());
        return $object;
    }

    protected function get38()
    {
        return $this->delegateContainer->get('dapr.actors');
    }

    protected function get39()
    {
        return $this->delegateContainer->get('dapr.actors.idle_timeout');
    }

    protected function get40()
    {
        return $this->delegateContainer->get('dapr.actors.scan_interval');
    }

    protected function get41()
    {
        return $this->delegateContainer->get('dapr.actors.drain_timeout');
    }

    protected function get42()
    {
        return $this->delegateContainer->get('dapr.actors.drain_enabled');
    }

    protected function get37()
    {
        $object = new Dapr\Actors\ActorConfig($this->get38(), $this->get39(), $this->get40(), $this->get41(), $this->get42());
        return $object;
    }

    protected function get44()
    {
        return $this->delegateContainer->get('Psr\\Log\\LoggerInterface');
    }

    protected function get45()
    {
        return $this->delegateContainer->get('Dapr\\Deserialization\\IDeserializer');
    }

    protected function get46()
    {
        return $this->delegateContainer->get('dapr.port');
    }

    protected function get43()
    {
        $object = new Dapr\DaprClient($this->get44(), $this->get45(), $this->get46());
        return $object;
    }

    protected function get48()
    {
        return $this->delegateContainer->get('dapr.serializers.custom');
    }

    protected function get47()
    {
        $object = new Dapr\Serialization\SerializationConfig($this->get48());
        return $object;
    }

    protected function get50()
    {
        return $this->delegateContainer->get('dapr.deserializers.custom');
    }

    protected function get49()
    {
        $object = new Dapr\Deserialization\DeserializationConfig($this->get50());
        return $object;
    }

    protected function get52()
    {
        return $this->delegateContainer->get('Dapr\\Actors\\Generators\\ProxyFactory');
    }

    protected function get53()
    {
        return $this->delegateContainer->get('Psr\\Log\\LoggerInterface');
    }

    protected function get51()
    {
        $object = new Dapr\Actors\ActorProxy($this->get52(), $this->get53());
        return $object;
    }

    protected function get55()
    {
        return $this->delegateContainer->get('dapr.pubsub.default');
    }

    protected function get56()
    {
        return $this->delegateContainer->get('DI\\FactoryInterface');
    }

    protected function get54()
    {
        $object = new Dapr\PubSub\Publish($this->get55(), $this->get56());
        return $object;
    }

    protected function get58()
    {
        return $this->delegateContainer->get('Psr\\Log\\LoggerInterface');
    }

    protected function get59()
    {
        return $this->delegateContainer->get('Dapr\\Actors\\ActorConfig');
    }

    protected function get60()
    {
        return $this->delegateContainer->get('DI\\FactoryInterface');
    }

    protected function get61()
    {
        return $this->delegateContainer->get('Dapr\\Deserialization\\IDeserializer');
    }

    protected function get57()
    {
        $object = new Dapr\Actors\ActorRuntime($this->get58(), $this->get59(), $this->get60(), $this->get61());
        return $object;
    }

    protected function get62()
    {
        return 'pubsub';
    }

}
